fix home path resolution at data_dir creation
LNP-BP/lnp-node pull request #23
Opened 2020-11-02 18:09 UTC by St333p

This is my "dirty" attempt to solve the issue we discussed about in #22. I realize it's not as clean as it could be (path gets converted from String to PathBuf to String to PathBuf again), but I'm not able to come up with anything better. Still it seems to work.

2020-11-02 18:17 UTC, dr-orlovsky requested changes
One suggestion, otherwise LGTM

2020-11-02 18:17 UTC, dr-orlovsky commented on src/opts.rs
> +        self.data_dir = PathBuf::from(data_dir);
I think we can go for

```suggestion
        let mut me = self.clone();
        me.data_dir = shellexpand::tilde(me.data_dir).to_string();
```

No need to use `process_dir` which also does `{data_dir}` substitution and opens attack vector with the call stack overflow

2020-11-02 18:24 UTC, St333p commented on src/opts.rs
> +        self.data_dir = PathBuf::from(data_dir);
I don't know why I stuck with using `process_dir`, like that it's definitely better.

2020-11-04 18:09 UTC, St333p commented on src/opts.rs
> +        self.data_dir = PathBuf::from(data_dir);
I needed to do some type conversions (in e4f7d13) to get it compile.

2020-11-04 21:00 UTC, merged